[functions.ai-chat]
verify_jwt = false

[functions.create-razorpay-order]
enabled = true
verify_jwt = false
import_map = "./functions/create-razorpay-order/deno.json"
entrypoint = "./functions/create-razorpay-order/index.ts"

[functions.verify-razorpay-payment]
enabled = true
verify_jwt = false
import_map = "./functions/verify-razorpay-payment/deno.json"
entrypoint = "./functions/verify-razorpay-payment/index.ts"

[functions.clerk-user-sync]
enabled = true
verify_jwt = true
import_map = "./functions/clerk-user-sync/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/clerk-user-sync/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/clerk-user-sync/*.html" ]
